import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers/Providers";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-main text-neutral-200`}>
				<Providers>
					<Navbar />
					<div className="flex flex-col min-h-custom">
						<div className="flex-grow">{children}</div>
						<Footer />
					</div>
				</Providers>
				<ToastContainer autoClose={3000} theme="dark" />
			</body>
		</html>
	);
}
